version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: -positron
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: -password
      MYSQL_PASSWORD: -password
      MYSQL_USER: -positron
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.0.4-apache
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql_data:
